name: Code Coverage

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js version 24.x
        uses: actions/setup-node@v5
        with:
          node-version: 24.x
      - run: npm i
      - run: npm run coverage
        env:
          CI: true
      - name: "Report Coverage"
        if: always()
        uses: davelosert/vitest-coverage-report-action@8ab049ff5a2c6e78f78af446329379b318544a1a # v2.8.3
