name: Code Coverage

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Set up Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version: 24.x
          cache: "npm"
      - name: Install dependencies
        run: npm i
      - name: Run coverage
        run: npm run coverage
        env:
          CI: true
      - name: "Report Coverage"
        if: always()
        uses: davelosert/vitest-coverage-report-action@c4bbc33a89b7ace0e63d35f1f7d4bcee31155a73
