name: Code Coverage

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - name: Use Node.js version 24.x
        uses: actions/setup-node@v7
        with:
          node-version: 24.x
      - run: npm i
      - run: npm run coverage
        env:
          CI: true
      - name: "Report Coverage"
        if: always()
        uses: davelosert/vitest-coverage-report-action@8b157684c6a6b259b97d45e72b44242865c0f6a5 # v2.12.2
