name: Code Coverage

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Install pnpm
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
    - name: Use Node.js version 22.x
      uses: actions/setup-node@v5
      with:
        node-version: 22.x
    - run: pnpm install
    - run: pnpm coverage
      env:
        CI: true
    - name: 'Report Coverage'
      if: always() 
      uses:  davelosert/vitest-coverage-report-action@8ab049ff5a2c6e78f78af446329379b318544a1a # v2.8.3