name: Release
on:
  push:
    branches:
      - main
    paths:
      - "package.json"
jobs:
  version:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      value: ${{ steps.get_version.outputs.value }}
      tagged: ${{ steps.tagged.outputs.tagged }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Extract version from package.json
        uses: sergeysova/jq-action@a3f0d4ff59cc1dddf023fc0b325dd75b10deec58
        id: get_version
        with:
          cmd: 'jq .version package.json -r'
      - name: Debug Version
        run: echo "VERSION=${{ steps.get_version.outputs.value }}"
      - name: 'Check: package version has corresponding git tag'
        id: tagged
        shell: bash
        run: git show-ref --tags --verify --quiet -- "refs/tags/v${{ steps.get_version.outputs.value }}" && echo "tagged=0" >> $GITHUB_OUTPUT || echo "tagged=1" >> $GITHUB_OUTPUT
  tag:
    runs-on: ubuntu-latest
    needs: version
    if: needs.version.outputs.value != '0.0.0' && needs.version.outputs.tagged == '1'
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Install pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      - name: Use Node.js version 22.x
        uses: actions/setup-node@v5
        with:
          node-version: 22.x
      - name: Install dependencies
        run: pnpm install
      - name: Build package
        run: pnpm build
      - name: Update npm
        run: npm install -g npm@latest
      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@a22cf08638b34d5badda920f9daf6e72c477b07b #v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: "v"
          custom_tag: ${{ needs.version.outputs.value }}
      - uses: ncipollo/release-action@b7eabc95ff50cbeeedec83973935c8f306dfcd0b #v1.20.0
        with:
          generateReleaseNotes: true
          skipIfReleaseExists: true
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}